[platformio]
default_envs = rp2040

[env:rp2040]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pico
framework = arduino
monitor_speed = 115200
board_build.core = earlephilhower
board_build.mcu = rp2040